[theme]

# Primary accent for interactive elements #173c6d
primaryColor = '#52983f'

# Background color for the main content area
backgroundColor = '#f0fff4'

# Background color for sidebar and most interactive widgets #93c98c
secondaryBackgroundColor = '#42649a'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "serif"
